### PR TITLE
added post via text feature

### PR DESCRIPTION
**Pull request by irinawilliamson**

### CODE REVIEW

**Review by achakka007 — COMMENTED** [review]
Good work getting Col and Row to work here. Try to avoid using specific dimensions and use flexbox instead please.

**Review by sts04038 — COMMENTED** [review]
looks good!

**Review by anthony789xue — COMMENTED** [review]
Everything looks good, clean and formatted code with no bugs

**Review by trenton-wong — COMMENTED** [review]
Looks solid, good use of Row/Col

**Review by awesomelemonade — APPROVED** [review]

**Pull request merged**
