### PR TITLE
Post via GitHub page + Private Popup

### PR DESCRIPTION
**Pull request by anthony789xue**
Post via GitHub page created with popup for private button

### CODE REVIEW

**Review by achakka007 — COMMENTED** [review]
Try not to use specific dimensions for components like images. Keep things flexible

**Review by irinawilliamson — COMMENTED** [review]
when adding an image, using a url is fine but I would add a new file for images and locally source it to the file that you're working on. that way we all have access to the image once you push your code.

**Review by sts04038 — COMMENTED** [review]
code looks good

**Review by irinawilliamson — COMMENTED** [review]
looks good!

**Review by trenton-wong — COMMENTED** [review]
Page looks good and the popup works well

**Review by awesomelemonade — APPROVED** [review]

**Pull request merged**
